### ISSUE TITLE
@config = default.dup.update(config)

### ISSUE THREAD

**Issue by SetScript** [ruby/webrick#150]
```
/usr/home/zennix/.local/share/gem/ruby/3.3/gems/webrick-1.8.2/lib/webrick/server.rb:89:in `update': no implicit conversion of String into Hash (TypeError)

      @config = default.dup.update(config)
                                   ^^^^^^
        from /usr/home/zennix/.local/share/gem/ruby/3.3/gems/webrick-1.8.2/lib/webrick/server.rb:89:in `initialize'
        from /usr/home/zennix/.local/share/gem/ruby/3.3/gems/webrick-1.8.2/lib/webrick/httpserver.rb:47:in `initialize'
        from src/main.rb:57:in `new'
        from src/main.rb:57:in `<main>'
[zennix@s12]:<~/y0d9>$
```

ruby version and host information:
```
[zennix@s12]:<~/y0d9>$ ruby -v
ruby 3.3.2 (2024-05-30 revision e5a195edf6) [amd64-freebsd14]
```

What did I do wrong? ;c

**Comment by jeremyevans** [comment]
It looks `config` is a string, but you need to provide a hash to `update`.
